<?php
//raspbian router online admin
//language file
session_start();
$_SESSION['preflang'] = $_SESSION['preflang']==''?'1033':$_SESSION['preflang'];
$langStr = array();
$langStr[1033] = array(
    "langName" => "English(en_US)",
    "isDefault" => "true",
    'username' => 'Username',
    "password" => "Password",
    "youhaveloggedinsuccessfully" => "You have logged in successfully!",
    "passwordincorrect" => "Password incorrect!",
    "youneedtologinfirst" => "You need to login first!",
    "login" => "Login",
    "captcha" => "Captcha",
    "year" => "year",
    "years" => "years",
    "month" => "month",
    "months" => "months",
    "day" => "day",
    "days" => "days",
    "hour" => "hr",
    "hours" => "hrs",
    "minute" => "min",
    "minutes" => "mins",
    "second" => "sec",
    "seconds" => "secs",
    "areyousuretologout" => "Are you sure to log out?",
    "logout" => "Logout",
    "Status" => "Status",
    "Language" => "Language",
    "close" => "Close",
    "captchaisincorrect" => "Captcha is incorrect!",
    "On" => "On",
    "Off" => "Off",
    'classdoesntexist' => 'Class doesn\'t exist! Exiting......',
    "emailisinvalid" => "Email is invalid",
    "usernamelengthshouldnotshorterthan4characters" => "Username length should not shorter than 4 characters!",
    "passwordshouldnotshorterthan6characters" => "Password should not shorter than 6 characters!",
    "passwordthatyouentered2timescannotmatcheachother" => "Password that you entered 2 times cannot match each other!",
    "pleaseenteryouremail" => "Please enter your email!",
    'yourschoolisnotsupportedbyus' => "Sorry, but your school is not supported by us.<br>However, you can choose to become a developer.<br>Please contact i@zxq.io for more info.",
    "confirmpassword" => "Confirm Password",
    "register" => "Register",
    "email" => "E-Mail",
    "youhadverifiedyouremailsuccessfully" => "You had verified your email successfully!",
    "verifyemailfailed" => "Verify E-Mail failed!",
    "s" => "s",
    "scheduleguideregistrationconfirmation" => "Schedule.guide() registration confirmation",
    "youhadregisteredsuccessfullypleaseconfirmyouremailfirst" => "You had registered successfully. Please confirm your email first.",
    "youhadloggedoutsuccessfully" => "You had logged out successfully!",
    "h" => "h",
    "pleaseinputalias" => "Please input alias",
    "thisaliasisusedbyanotherschedule" => "This alias is used by another schedule",
    "pleasetryanotheralias" => "Please try another alias",
    "calendardoesntexist" => "Calendar doesn't exist",
    "myschedulelist" => "My Schedule List",
    "pleaseloginfirst" => "Please Login First!",
    "thisisanerrorcontactadmin" => "This is an error, contact admin.",
    "registeremailcontent" => '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body><center><p>Hi! Welcome to Schedule.guide()!</p><p>You had already registered the website.</p><p>Please confirm you are a student from your school (and confirm the email) via the link below.</p><p><a href="https://schedule.guide/validateemail.php?id=%d&key=%s">https://schedule.guide/validateemail.php?id=%d&key=%s</a></p><p>After you validate your email, you can use your account.</p><p>We appreciate all kinds of suggestions since this is a beta version.</p><p>Thanks for using our service!</p><p>Please remember the website: <a href="https://schedule.guide/">https://schedule.guide/</a></p><p>Thanks again for using this website!</p><p></p><p>Founder: zhxq (i@zxq.io)</p><p>%s</p></center></body></html>',
    "usernameisoccupiedbyothers" => 'Username %s is occupied by others!',
    "emailisoccupiedbyothers" => 'Email %s is occupied!',
    "nextpage" => "Next Page",
    "previouspage" => "Previous Page",
    "firstpage" => "First Page",
    "lastpage" => "Last Page",
    "areyousuretodelete" => "Are you sure to DELETE?",
    "total:records" => "Total: %d record(s)",
    "currentpage:" => "Current Page: %d"
);
$langStr[2052] = array(
    "langName" => "简体中文(zh_CN)",
    "isDefault" => "false",
    'username' => '用户名',
    "password" => "密码",
    "youhaveloggedinsuccessfully" => "您已经成功登陆！",
    "passwordincorrect" => "密码错误！",
    "youneedtologinfirst" => "请您先登录！",
    "login" => "登录",
    "captcha" => "验证码",
    "year" => "年",
    "years" => "年",
    "month" => "月",
    "months" => "月",
    "day" => "日",
    "days" => "日",
    "hour" => "时",
    "hours" => "时",
    "minute" => "分",
    "minutes" => "分",
    "second" => "秒",
    "seconds" => "秒",
    "areyousuretologout" => "您确定登出么？",
    "logout" => "登出",
    "Status" => "状态",
    "Language" => "语言",
    "close" => "关闭",
    "shadowsocksredirectstatus" => "Shadowsocks转发状态",
    "On" => "开",
    "Off" => "关",
    "usernamelengthshouldnotshorterthan4characters" => "用户名不得小于四个字符！",
    "passwordshouldnotshorterthan6characters" => "密码长度小于6个字符，请检查！",
    "passwordthatyouentered2timescannotmatcheachother" => "两次密码不符，请检查！",
    "pleaseenteryouremail" => "Email地址不能为空！",
    'yourschoolisnotsupportedbyus' => "抱歉，您的学校不在我们的服务列表内。",
    "confirmpassword" => "确认密码",
    "register" => "注册",
    "email" => "E-Mail",
    "youhadverifiedyouremailsuccessfully" => "您已经成功验证邮箱!",
    "verifyemailfailed" => "验证邮箱失败!",
    "detailsettings" => "详细设置",
    "saveandrestartss" => "保存并重启Shadowsocks",
    "serverip" => "服务器IP",
    "serverport" => "服务器端口",
    "locallisteningport" => "本地监听端口",
    "connectiontimeout" => "连接超时时间",
    "s" => "秒",
    "scheduleguideregistrationconfirmation" => "Schedule.guide() 注册确认邮件",
    "youhadregisteredsuccessfullypleaseconfirmyouremailfirst" => "您已注册成功，请您先验证邮箱。",
    "youhadloggedoutsuccessfully" => "您已成功登出!",
    "h" => "小时",
    "pleaseinputalias" => "请输入一个名称",
    "iprangefrom" => "IP段起点",
    "iprangeto" => "至",
    "myschedulelist" => "我的日历列表",
    "saveandrestartnetwork" => "保存并重启网络",
    "pleaseloginfirst" => "请先登录!",
    "thisisanerrorcontactadmin" => "出错了，请联系管理员~",
    "registeremailcontent" => '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body><center><p>Hi! Welcome to Schedule.guide()!</p><p>You had already registered the website.</p><p>Please confirm you are a student from your school (and confirm the email) via the link below.</p><p><a href="https://schedule.guide/validateemail.php?id=%d&key=%s">https://schedule.guide/validateemail.php?id=%d&key=%s</a></p><p>After you validate your email, you can use your account.</p><p>We appreciate all kinds of suggestions since this is a beta version.</p><p>Thanks for using our service!</p><p>Please remember the website: <a href="https://schedule.guide/">https://schedule.guide/</a></p><p>Thanks again for using this website!</p><p></p><p>Founder: zhxq (i@zxq.io)</p><p>%s</p></center></body></html>',
    "usernameisoccupiedbyothers" => '用户名 %s 已被占用!',
    "emailisoccupiedbyothers" => 'Email %s 已被占用!',
);
function __($strName){
    global $langStr;
    return $langStr[$_SESSION['preflang']][$strName];
}

?>